name: Magalix
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  magalix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Magalix
        uses: magalixcorp/magalix-action@main
        with:
          webhook: https://console.magalix.com/api/v1/kubeguard/37a381c8-8be9-48cd-a78c-eb6942884a0d/e4cd9595-19d9-4e8d-a423-6af3b273d133
